version: "3.8"
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: ${COMPOSE_PROJECT_NAME}:7.4.3-apache
    container_name: ${COMPOSE_PROJECT_NAME}_web
    restart: "always"
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ../src:/var/www/html
  database:
    image: arm64v8/mysql:oracle
    container_name: ${COMPOSE_PROJECT_NAME}_database
    restart: always
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
